### ISSUE TITLE
AttributeError: 'Darknet' object has no attribute 'module'

### ISSUE THREAD

**Issue by elixir-1** [marvis/pytorch-yolo2#109]
I am trying to train on y own dataset with GPU. Changed the cfg/voc.data accordingly. 
On running the command python3 train, I get the following error: 
Traceback (most recent call last):
  File "train.py", line 262, in <module>
    train(epoch)
  File "train.py", line 130, in train
    cur_model = model.module
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 532, in __getattr__
    type(self).__name__, name))
AttributeError: 'Darknet' object has no attribute 'module'

**Comment by waseem6383** [comment]
I have solve this issue thanks :)

**Comment by Sunyouteng** [comment]
@waseem6383 @elixir-1 @marvis  how did you solve this problem? I don't have GPU. After I change `use_cuda      = False` in train.py, this error happens.
