### ISSUE TITLE
How fast it is?

### ISSUE THREAD

**Issue by onlytailei** [marvis/pytorch-yolo2#11]
Real time or not?

**Comment by c0nn3r** [comment]
It's real time. On a Titan X, I get over 100+ frames for a second.

**Comment by c0nn3r** [comment]
Sadly, I keep running into bugs. :cry:

**Comment by marvis** [comment]
@onlytailei about 140fps to train pascal voc data on titan x. you can add more workers if loading data is a problem.

**Comment by marvis** [comment]
@c0nn3r I also met a lot of problems and fix with days or weeks. Hope we can make this tool better.

**Comment by acrosson** [comment]
I downloaded the weights from `http://pjreddie.com/media/files/yolo.weights` and ran `python detect.py cfg/yolo.cfg yolo.weights data/dog.jpg`. I'm getting the following speed:
```
 image to tensor : 0.002531
  tensor to cuda : 0.001471
         predict : 0.175203
get_region_boxes : 0.002339
             nms : 0.000088
           total : 0.181632
-----------------------------------
```

Am I missing something? This is running on GTX 1080 Ti.
