### ISSUE TITLE
 a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by leadcain84** [marvis/pytorch-yolo2#112]
when I run the train.py, type error is occurs.
How can I fix it?

python train.py cfg/voc.data cfg/yolo-voc.cfg weight/darknet19_448.conv.23
  File "train.py", line 44, in <module>
    nsamples      = file_lines(trainlist)
  File "/bjkim/DL/pytorch/pytorch-yolo2/utils.py", line 396, in file_lines
    count += buffer.count('\n')
  TypeError: a bytes-like object is required, not 'str'

**Comment by leadcain84** [comment]
I solved it.
the problem is environment version.
my env.
pythjon=3.6
pytorch=0.4, py36_cuda8.0.61_cudnn7.1.2_1
torchvision=0.2.1
cudatoolkit=8.0

and edit some codes for python3.6
https://github.com/marvis/pytorch-yolo2/pull/58/commits/bfc1cafd600c29a57a2740fba32790131f51e83c

**Comment by leeneil** [comment]
You can fix this by replacing 

`count += buffer.count('\n')
`
with 

`count += buffer.count('\n'.encode())`

**Comment by lizilongcn** [comment]
Thanks，leeneil. It works for me

**Comment by ntelo007** [comment]
Hi there!

When I run the following code: 
~~~
...
    if write and is_train:
        train_loss_file.write(
            "[%d], Loss:%.5f, Loss(VecMap):%.5f, Pixel Accuracy:%.3f, Mean Accuracy:%.3f, Mean IoU:%.3f, Class IoU:[%.5f/%.5f], Freq.Weighted Accuray:%.3f  \n"
            % (
                epoch,
                loss,
                loss_vec,
                100 * pixel_accuracy,
                100 * np.nanmean(mean_accuracy),
                100 * np.nanmean(mean_iou),
                mean_iou[0],
                mean_iou[1],
                (100 * fwavacc),
            )
        )
...
~~~

I get the following error:
~~~
[>....... 1/1 ............]S:25s968ms|T:0ms|Loss: -0.199331 | VecLoss: 3.783525 | road miou: 17.2746%(18.3798%) | angle miou: 0.2103%
Traceback (most recent call last):
  File "train_mtl.py", line 443, in <module>
    main()
  File "train_mtl.py", line 434, in main
    train(epoch)
  File "train_mtl.py", line 294, in train
    write=True,
  File "C:\Users\kaniourasp\Downloads\Thesis\road_connectivity-master\road_connectivity-master\utils\util.py", line 147, in performMetrics
    (100 * fwavacc),
TypeError: a bytes-like object is required, not 'str'
~~~

![image](https://user-images.githubusercontent.com/31326655/69955293-a7a34d00-14fd-11ea-8938-b54a990f72ba.png)

![image](https://user-images.githubusercontent.com/31326655/69955331-b558d280-14fd-11ea-8802-eb7e655f4ecb.png)

In the attached images you can see the packages that I have installed for this project.

Can you please help me overcome this issue? I tried @leeneil 's suggestion but it didn't work.
