### ISSUE TITLE
Got nan when training

### ISSUE THREAD

**Issue by robotcator** [marvis/pytorch-yolo2#12]
Hi, I use the voc-2007 data to train the model, but after several epoch, it got the nan for total loss. The only thing I do is to modify the batch size to 16 because of the memory limitation.

`python train.py cfg/voc.data cfg/yolo-voc.cfg darknet19_448.conv.23`

```
7731: nGT 46, recall 26, proposals 0, loss: x 2.349184, y 2.490905, w 4.355775, h 3.614321, conf 39.847290, cls 65.046005, total 117.703484
7747: nGT 44, recall 25, proposals 0, loss: x 2.036328, y 2.825909, w 5.378100, h 3.541537, conf 31.159536, cls 77.241898, total 122.183304
7763: nGT 43, recall 23, proposals 0, loss: x 2.423934, y 2.169328, w 7.056859, h 4.760055, conf 31.776106, cls 65.494301, total 113.680588
7779: nGT 36, recall 22, proposals 0, loss: x 2.323455, y 2.308568, w 4.022618, h 3.688318, conf 28.542833, cls 62.400215, total 103.286011
7795: nGT 63, recall 33, proposals 0, loss: x 2.688333, y 3.176172, w 12.635139, h 8.774524, conf 46.178150, cls 61.022907, total 134.475220
7811: nGT 39, recall 27, proposals 0, loss: x 2.379846, y 1.757976, w 5.132181, h 3.417757, conf 34.402504, cls 56.947430, total 104.037689
7827: nGT 26, recall 19, proposals 0, loss: x 1.712508, y 1.285329, w 4.546144, h 3.727901, conf 22.661488, cls 32.598804, total 66.532173
7843: nGT 54, recall 27, proposals 0, loss: x 2.488572, y 2.801939, w 6.946329, h 3.782595, conf 35.892937, cls 73.443375, total 125.355743
7859: nGT 53, recall 23, proposals 0, loss: x 2.873883, y 2.228354, w 9.620174, h 8.059924, conf 33.462841, cls 56.902000, total 113.147179
7875: nGT 27, recall 24, proposals 0, loss: x 1.595567, y 1.694615, w 2.479064, h 1.932266, conf 29.289560, cls 33.758469, total 70.749542
7891: nGT 43, recall 23, proposals 0, loss: x 2.636100, y 2.269567, w 5.915263, h 7.448276, conf 33.041416, cls 69.943787, total 121.254410
7907: nGT 33, recall 25, proposals 0, loss: x 1.653842, y 1.759133, w 2.661319, h 3.565507, conf 31.916258, cls 50.097813, total 91.653870
7923: nGT 61, recall 32, proposals 0, loss: x 2.956027, y 3.122195, w 8.542360, h 6.390560, conf 45.510933, cls 76.769257, total 143.291336
7939: nGT 34, recall 26, proposals 0, loss: x 1.860917, y 2.053040, w 3.110031, h 2.572486, conf 32.622650, cls 39.233501, total 81.452621
7955: nGT 51, recall 28, proposals 0, loss: x 2.481926, y 2.717225, w 8.577497, h 5.421611, conf 38.322369, cls 62.287849, total 119.808472
7971: nGT 40, recall 24, proposals 0, loss: x 2.172042, y 2.205583, w 7.389314, h 4.208218, conf 32.074078, cls 47.150154, total 95.199387
7987: nGT 38, recall 27, proposals 0, loss: x 2.350132, y 2.203409, w 5.121133, h 3.327881, conf 34.168556, cls 71.289795, total 118.460907
8003: nGT 45, recall 29, proposals 0, loss: x 2.186419, y 2.192357, w 4.423503, h 4.970468, conf 34.720768, cls 78.276001, total 126.769516
8019: nGT 37, recall 20, proposals 0, loss: x 1.855428, y 1.746336, w 39.110874, h 18.282925, conf 28.785917, cls 44.943192, total 134.724670
8035: nGT 46, recall 13, proposals 0, loss: x 2.211419, y 2.723539, w 1913.079834, h 674.672302, conf 19.403646, cls 69.387505, total 2681.478027
8051: nGT 30, recall 1, proposals 126, loss: x 4.607321, y 3.702282, w 22283.521484, h 8063.946289, conf 112.698860, cls 62.117603, total 30530.593750
8067: nGT 56, recall 3, proposals 8, loss: x 6.746982, y 7.706589, w 37403.359375, h 18961.296875, conf 16.680902, cls 147.303436, total 56543.093750
8083: nGT 68, recall 0, proposals 247, loss: x 5.968837, y 5.557522, w 420457.593750, h 287265.812500, conf 272.219299, cls 196.477310, total 708203.687500
8099: nGT 36, recall 1, proposals 223, loss: x 5.042193, y 6.670439, w 7483772.000000, h 3956476.000000, conf 1657.315186, cls 102.241219, total 11442019.000000
8115: nGT 33, recall 0, proposals 161, loss: x 238.091919, y 146.132980, w 25007292416.000000, h 7837334528.000000, conf nan, cls 170.704361, total nan
8131: nGT 39, recall 0, proposals 0, loss: x 1691.090332, y 1691.476074, w inf, h inf, conf nan, cls nan, total nan
8147: nGT 51, recall 0, proposals 0, loss: x 1690.921631, y 1691.080078, w nan, h nan, conf nan, cls nan, total nan
8163: nGT 42, recall 0, proposals 0, loss: x 1691.757935, y 1691.083496, w nan, h nan, conf nan, cls nan, total nan
8179: nGT 37, recall 0, proposals 0, loss: x 1691.634521, y 1690.699463, w nan, h nan, conf nan, cls nan, total nan
8195: nGT 36, recall 0, proposals 0, loss: x 1691.959961, y 1691.344360, w nan, h nan, conf nan, cls nan, total nan
8211: nGT 37, recall 0, proposals 0, loss: x 1692.251587, y 1691.887939, w nan, h nan, conf nan, cls nan, total nan
8227: nGT 35, recall 0, proposals 0, loss: x 1692.250122, y 1691.189697, w nan, h nan, conf nan, cls nan, total nan
8243: nGT 34, recall 0, proposals 0, loss: x 1691.465332, y 1692.634277, w nan, h nan, conf nan, cls nan, total nan

```

**Comment by marvis** [comment]
Maybe the learning rate is large. Have you used the warmup training?

**Comment by robotcator** [comment]
What do you mean "warm up training", you mean finetune on the darknet19_448?

**Comment by marvis** [comment]
learning_rate=0.001
burn_in=1000
max_batches = 80200
policy=steps
steps=-1,500,40000,60000
scales=0.1,10,.1,.1

the first 500 batches need a much smaller learning rate

**Comment by btekin** [comment]
I also had the same issue when I used a batch size of 16 due to limited GPU memory. Using a smaller initial learning rate of 0.00025 resolved the nan issue, although I am not sure yet if it is gonna yield good convergence. With a smaller batch size, the gradients become more unstable, so in this case a smaller learning rate might be needed. 

In train.py the SGD is defined as follows:

optimizer = optim.SGD(model.parameters(), lr=learning_rate/batch_size, momentum=momentum, dampening=0, weight_decay=decay*batch_size)

@marvis Could you explain why you are dividing the learning rate by the batch size (and also multiply the decay by the batch size)? This could actually be the reason for gradient explosion as learning_rate/batch_size is getting larger with a smaller learning rate.

**Comment by marvis** [comment]
learning_rate/batch_size: see https://github.com/pjreddie/darknet/blob/master/src/convolutional_layer.c#L530

decay * batch_size: see
https://github.com/pjreddie/darknet/blob/master/src/convolutional_layer.c#L529

**Comment by btekin** [comment]
I see, thanks.

**Comment by robotcator** [comment]
@marvis @btekin  Thanks for your advice. Now, It seems that works well, but still can not get the darknet's training result.

**Comment by marvis** [comment]
@robotcator what's your best result？

**Comment by robotcator** [comment]
I use the VOC_2007 training data with 5011 samples. Use batch size 16 and modify the learning_rate to 0.00025. All other parameters use default values, I evaluate the training result and got :
```
2017-08-08 10:07:29 evaluating ...
2017-08-08 10:07:57 precision: 0.496957, recall: 0.481962, fscore: 0.489340
```
maybe I forget to modify the max_epochs for the reason that max_epochs has relation with the sample size. https://github.com/marvis/pytorch-yolo2/blob/master/train.py#L51

**Comment by marvis** [comment]
Can you fellow the fellowing steps to prepare the train data? The total number of training images is 16551.

Get The Pascal VOC Data
wget https://pjreddie.com/media/files/VOCtrainval_11-May-2012.tar
wget https://pjreddie.com/media/files/VOCtrainval_06-Nov-2007.tar
wget https://pjreddie.com/media/files/VOCtest_06-Nov-2007.tar
tar xf VOCtrainval_11-May-2012.tar
tar xf VOCtrainval_06-Nov-2007.tar
tar xf VOCtest_06-Nov-2007.tar
Generate Labels for VOC

wget http://pjreddie.com/media/files/voc_label.py
python voc_label.py
cat 2007_train.txt 2007_val.txt 2012_*.txt > voc_train.txt

**Comment by zeynali** [comment]
@robotcator , Hi , did you solve your problem ? when i run : 
`python train.py cfg/voc.data cfg/tiny-yolo-voc.cfg darknet19_448.conv.23`

GTX 1080 , ubuntu 16.04 , PyTorch0.3.1 , python2.7 , cuda8.0
####################################

```
37381: nGT 48, recall 31, proposals 0, loss: x 1.634392, y 1.738499, w 4.785542, h 3.373857, conf 38.835564, cls 81.443108, total 131.810959
37397: nGT 45, recall 26, proposals 0, loss: x 1.411715, y 1.993875, w 3.049723, h 2.952906, conf 34.241985, cls 75.332039, total 118.982239
37413: nGT 33, recall 21, proposals 0, loss: x 1.453969, y 1.320857, w 2.299419, h 1.156732, conf 24.711887, cls 64.829071, total 95.771935
37429: nGT 42, recall 28, proposals 0, loss: x 1.495622, y 1.920833, w 2.795640, h 1.830215, conf 34.136925, cls 88.607285, total 130.786530
37445: nGT 46, recall 30, proposals 0, loss: x 2.423537, y 1.785112, w 2.755303, h 0.927903, conf 39.327442, cls 93.342468, total 140.561768
37461: nGT 41, recall 27, proposals 0, loss: x 2.367318, y 1.578801, w 3.257559, h 2.610318, conf 35.038498, cls 80.100639, total 124.953133
37477: nGT 35, recall 19, proposals 0, loss: x 1.184399, y 1.251219, w 1.974485, h 2.145396, conf 26.266386, cls 71.499397, total 104.321281
37493: nGT 32, recall 22, proposals 0, loss: x 1.314279, y 0.953480, w 1.866040, h 1.576841, conf 25.505089, cls 76.279274, total 107.495003
37509: nGT 41, recall 30, proposals 0, loss: x 1.327371, y 1.915355, w 2.556979, h 2.188304, conf 35.723034, cls 88.609505, total 132.320557
37525: nGT 34, recall 26, proposals 0, loss: x 1.075980, y 1.255369, w 3.663902, h 0.802038, conf 33.380516, cls 56.296627, total 96.474434
37541: nGT 43, recall 33, proposals 0, loss: x 1.768308, y 1.962864, w 1.742663, h 1.449004, conf 36.097939, cls 83.223137, total 126.243912
37557: nGT 27, recall 16, proposals 0, loss: x 0.856905, y 0.665262, w 3.756028, h 0.882786, conf 24.303017, cls 73.063866, total 103.527863

```

**Comment by edgarmedina1801** [comment]
@zeynali I am having the same problem. I trained Yolov2 using the default configuration, and I got similar behavior but in different epochs (or iterations). Does someone know the why?

**Comment by zeynali** [comment]
@edgarmedina1801 , what's your GPU ?

**Comment by edgarmedina1801** [comment]
I tested on GTX980ti (6GBs) com minibatch=16 LR=2.5e-4 ;  e  2 - K80 (24GB both) with default configuration. I have another with 2 TitanX (24GB) but I didn't test anything on that.

thanks in advanced

**Comment by edgarmedina1801** [comment]
oh sorry, I didn't complete the training, an error occurred after epoch 70. Even when I use Minibatch=16

RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

**Comment by ayooshkathuria** [comment]
@zeynali Getting the same issues related to proposals dropping to zero after few epochs. I didn't have the time to train for onger (will do shortly). So just wanted to ask how you results have been? 

Using a Tesla K80 on Ubuntu 16.04, Python 2.7.12 and PyTorch 0.4.
