### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by ydc123** [marvis/pytorch-yolo2#120]
Hi, I faced a bug when I was training.
At the beginning of training, everything was ok
![image](https://user-images.githubusercontent.com/23184884/42092893-1d87aba8-7bdd-11e8-8917-ecc40c94322d.png)
![image](https://user-images.githubusercontent.com/23184884/42092909-291f5222-7bdd-11e8-8d5a-841494adbaa9.png)
But after some epochs, my process stopped
![image](https://user-images.githubusercontent.com/23184884/42092795-c6dcbc76-7bdc-11e8-9d80-59380b1b3e5e.png)
When I used 'watch nvidia-smi', I saw
![image](https://user-images.githubusercontent.com/23184884/42093014-862db2d8-7bdd-11e8-930d-93d3c39096d3.png)
Is there anyone can give me some hints? Thank you and sorry for my bad English.

**Comment by wxjeacen** [comment]
Reduce the batch size.

**Comment by ydc123** [comment]
@wxjeacen  Thank you, I solve it. Multi-scale training will increase the memory, so I encounter it after some epochs

**Comment by puyangma** [comment]
@ydc123 May I ask how did you solve the multi-scale OOM error? Just decreasing the batch size?

**Comment by ydc123** [comment]
> @ydc123 May I ask how did you solve the multi-scale OOM error? Just decreasing the batch size?

right

**Comment by puyangma** [comment]
@ydc123 Thanks for your reply. What was the final batch size you used?

**Comment by ydc123** [comment]
> @ydc123 Thanks for your reply. What was the final batch size you used?

I don't remember and I think it is related to your machine

**Comment by puyangma** [comment]
@ydc123 Okay Thanks!
