### ISSUE TITLE
best_iou computation

### ISSUE THREAD

**Issue by btekin** [marvis/pytorch-yolo2#13]
In region_loss.py, "best_iou" parameter that determines which predictor is responsible for detection is set to the index that gives the highest IOU between the _pre-computed anchor boxes_ and the ground-truth box. I think that IOU should instead be computed between the predictions and the ground-truth boxes.

In the first YOLO paper, it is written as follows

> At training time we only want one bounding box predictor to be responsible for each object. We assign one predictor to be "responsible" for predicting an object based on which prediction has the highest current IOU with the ground truth. This leads to specialization between the bounding box predictors.

In an earlier paragraph, it is mentioned that

> If the center of an object falls into a grid cell, that grid cell is responsible for detecting that object.

Checking the original darknet implementation (https://github.com/pjreddie/darknet/blob/master/src/region_layer.c#L265:L274), in my understanding, while computing the best_iou, the author does not use the anchor boxes but rather the "predictors" at the grid location corresponding to the center of the ground-truth (truth.x and truth.y) object. 

So, in my opinion, there is a confusion between the "anchors" and the "predictors" and Lines 67-95 of the region_loss.py function (https://github.com/marvis/pytorch-yolo2/blob/master/region_loss.py#L67:L95) should be revised and fixed.

**Comment by marvis** [comment]
@btekin  Please see https://github.com/pjreddie/darknet/blob/master/src/region_layer.c#L275:L281. After predict, the pred boxes is reset to anchor's width and height.

**Comment by btekin** [comment]
You are right, thanks for clarifying!

**Comment by marvis** [comment]
@btekin Cheers!
