### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer in demo.py

### ISSUE THREAD

**Issue by kumarvis** [marvis/pytorch-yolo2#133]
While running **demo.py** on my own generated weight from YOLOv2 darknet package I face the below error. PyTorch Version CPU support 0.4.1 
TypeError: 'float' object cannot be interpreted as an integer. 
While debugging I find it is thrown by below line. 
https://github.com/marvis/pytorch-yolo2/blob/6c7c1561b42804f4d50d34e0df220c913711f064/darknet.py#L91

**I have changes the demo.py  to perform the test from folder like below**

def demo(cfgfile, weightfile):
    
    m = Darknet(cfgfile)
    m.print_network()
    m.load_weights(weightfile)
    print('Loading weights from %s... Done!' % (weightfile)) ## i got this printed 

    namesfile = 'configs/lbl.names'
    class_names = load_class_names(namesfile)
 
    use_cuda = False  ##this is changed
    if use_cuda:
        m.cuda()

    img_path_list = get_img_list('/home/user/test_images/', 'png')
    for img_path in img_path_list:
        img = cv2.imread(img_path)
        sized = cv2.resize(img, (m.width, m.height))
        bboxes = do_detect(m, sized, 0.5, 0.4, use_cuda)
        draw_img = plot_boxes_cv2(img, bboxes, None, class_names)
        print('It passes DONE')
        cv2.imshow(cfgfile, draw_img)
        cv2.waitKey(1)

**Comment by kumarvis** [comment]
https://github.com/marvis/pytorch-yolo2/issues/129 
Followed the steps properly solved my problem . As I missed the padding thing initially.

**Comment by sxs11** [comment]
Is your python version 3? I don't have this error when I use Python2

**Comment by kumarvis** [comment]
Hi @sxs11 I have python3 only but as you can see I have closed it with reference.
