### ISSUE TITLE
how to run this with torch 0.4

### ISSUE THREAD

**Issue by Sunyouteng** [marvis/pytorch-yolo2#142]
hello, i want to run this with torch 0.4. and I encounter many errors.
for example:
2018-10-28 16:34:49 epoch 0, processed 0 samples, lr 0.000100
Traceback (most recent call last):
File "train.py", line 262, in
train(epoch)
File "train.py", line 168, in train
loss = region_loss(output, target)
File "/home/yruijia/pytorch-ylo2/newenv/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in call
result = self.forward(input, **kwargs)
File "/home/yruijia/pytorch-ylo2/region_loss.py", line 142, in forward
pred_boxes[0] = x.data + grid_x
RuntimeError: The size of tensor a (13) must match the size of tensor b (27040) at non-singleton dimension 3
After i make some changes as other's help
for example:
pred_boxes[0] = torch.reshape(x.data(1,nBnAnHnW)) + grid_x,
pred_boxes[1] = torch.reshape(y.data(1,nBnAnHnW)) + grid_y
pred_boxes[2] = torch.reshape(torch.exp(w.data)(1,nBnAnHnW)) * anchor_w
pred_boxes[3] = torch.reshape(torch.exp(h.data)(1,nBnAnH*nW)) * anchor_h

then the error is:
Traceback (most recent call last):
File "train.py", line 262, in
train(epoch)
File "train.py", line 168, in train
loss = region_loss(output, target)
File "/home/yruijia/pytorch-ylo2/newenv/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in call
result = self.forward(input, **kwargs)
File "/home/yruijia/pytorch-ylo2/region_loss.py", line 142, in forward
pred_boxes[0] = torch.reshape(x.data(1,nBnAnHnW)) + grid_x
TypeError: 'Tensor' object is not callable
Then i dont know how to do with this??
So can anyone give a summery of the change of your version which can run with torch 0.4.
thanks a lot if you reply!

**Comment by fangziyi0904** [comment]
I have same error.Can you solve it?

**Comment by fangziyi0904** [comment]
> hello, i want to run this with torch 0.4. and I encounter many errors.
> for example:
> 2018-10-28 16:34:49 epoch 0, processed 0 samples, lr 0.000100
> Traceback (most recent call last):
> File "train.py", line 262, in
> train(epoch)
> File "train.py", line 168, in train
> loss = region_loss(output, target)
> File "/home/yruijia/pytorch-ylo2/newenv/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in call
> result = self.forward(input, **kwargs)
> File "/home/yruijia/pytorch-ylo2/region_loss.py", line 142, in forward
> pred_boxes[0] = x.data + grid_x
> RuntimeError: The size of tensor a (13) must match the size of tensor b (27040) at non-singleton dimension 3
> After i make some changes as other's help
> for example:
> pred_boxes[0] = torch.reshape(x.data(1,nBnAnHnW)) + grid_x,
> pred_boxes[1] = torch.reshape(y.data(1,nBnAnHnW)) + grid_y
> pred_boxes[2] = torch.reshape(torch.exp(w.data)(1,nBnAnHnW)) * anchor_w
> pred_boxes[3] = torch.reshape(torch.exp(h.data)(1,nBnAnH*nW)) * anchor_h
> 
> then the error is:
> Traceback (most recent call last):
> File "train.py", line 262, in
> train(epoch)
> File "train.py", line 168, in train
> loss = region_loss(output, target)
> File "/home/yruijia/pytorch-ylo2/newenv/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in call
> result = self.forward(input, **kwargs)
> File "/home/yruijia/pytorch-ylo2/region_loss.py", line 142, in forward
> pred_boxes[0] = torch.reshape(x.data(1,nBnAnHnW)) + grid_x
> TypeError: 'Tensor' object is not callable
> Then i dont know how to do with this??
> So can anyone give a summery of the change of your version which can run with torch 0.4.
> thanks a lot if you reply!

I have same error.Can you solve it?

**Comment by RamyaRaghuraman** [comment]
Hi @Sunyouteng @fangziyi0904 ,

Was anyone able to solve this issue?
