### ISSUE TITLE
When i use   ''python demo.py cfg/tiny-yolo-voc.cfg tiny-yolo-voc.weights''

### ISSUE THREAD

**Issue by Zouhanyu123** [marvis/pytorch-yolo2#160]
I use ''yolov2-tiny.weights' and rename it to ’‘tiny-yolo-voc.weight’‘s and then run ''python demo.py cfg/tiny-yolo-voc.cfg tiny-yolo-voc.weights'', which happens Following error

Traceback (most recent call last):
  File "demo.py", line 46, in <module>
    demo(cfgfile, weightfile)
  File "demo.py", line 8, in demo
    m.load_weights(weightfile)
  File "E:\Python program\pytorch-yolo2-master\darknet.py", line 265, in load_weights
    start = load_conv_bn(buf, start, model[0], model[1])
  File "E:\Python program\pytorch-yolo2-master\cfg.py", line 186, in load_conv_bn
    conv_model.weight.shape[0], conv_model.weight.shape[1], conv_model.weight.shape[2], conv_model.weight.shape[3])));
RuntimeError: shape '[1024, 1024, 3, 3]' is invalid for input of size 4934570

I use pytorch 0.41

Well, when I changed a weight and successfully ran the code, but no checkbox appeared

**Comment by pulkit15158** [comment]
you can refer https://github.com/marvis/pytorch-yolo2/issues/158#issue-454838425.
USed similar weights
