### ISSUE TITLE
IndexError: The shape of the mask [845] at index 0does not match the shape of the indexed tensor [5, 13, 13] at index 0

### ISSUE THREAD

**Issue by kingkedar** [marvis/pytorch-yolo2#172]
python train.py cfg/voc.data cfg/yolo-voc.cfg darknet19_448.conv.23
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  32
    1 max          2 x 2 / 2   416 x 416 x  32   ->   208 x 208 x  32
    2 conv     64  3 x 3 / 1   208 x 208 x  32   ->   208 x 208 x  64
    3 max          2 x 2 / 2   208 x 208 x  64   ->   104 x 104 x  64
    4 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    5 conv     64  1 x 1 / 1   104 x 104 x 128   ->   104 x 104 x  64
    6 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    7 max          2 x 2 / 2   104 x 104 x 128   ->    52 x  52 x 128
    8 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256
    9 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128
   10 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256
   11 max          2 x 2 / 2    52 x  52 x 256   ->    26 x  26 x 256
   12 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   13 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256
   14 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   15 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256
   16 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   17 max          2 x 2 / 2    26 x  26 x 512   ->    13 x  13 x 512
   18 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   19 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512
   20 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   21 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512
   22 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   23 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   24 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   25 route  16
   26 conv     64  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x  64
   27 reorg              / 2    26 x  26 x  64   ->    13 x  13 x 256
   28 route  27 24
   29 conv   1024  3 x 3 / 1    13 x  13 x1280   ->    13 x  13 x1024
   30 conv    125  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 125
   31 detection
2019-11-06 16:17:20 epoch 0, processed 0 samples, lr 0.000100
/home/kedar/anaconda3/envs/2.7/lib/python2.7/site-packages/torch/nn/functional.py:1351: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "train.py", line 266, in <module>
    train(epoch)
  File "train.py", line 172, in train
    loss = region_loss(output, target)
  File "/home/kedar/anaconda3/envs/2.7/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kedar/Downloads/API-SIM/framework_to_onnx/pytorch-yolo2-master/region_loss.py", line 157, in forward
    nH, nW, self.noobject_scale, self.object_scale, self.thresh, self.seen)
  File "/home/kedar/Downloads/API-SIM/framework_to_onnx/pytorch-yolo2-master/region_loss.py", line 38, in build_targets
    conf_mask[b][cur_ious>sil_thresh] = 0
IndexError: The shape of the mask [845] at index 0does not match the shape of the indexed tensor [5, 13, 13] at index 0

**Comment by DeepLearning723** [comment]
Hi, I meet the same issue. 
The shape of the mask [845] at index 0does not match the shape of the indexed tensor [5, 13, 13] at index 0.
Did you solve this problem? I don't know how to modify. Thanks a lot.

**Comment by wudi00** [comment]
I met the same problem. Have you solved this problem？Thanks.

**Comment by Aaronponceuv** [comment]
I had its problem when apply
conf_mask  = torch.ones(nB, nA, nH, nW) * noobject_scale
conf_mask = conf_mask.view(nB, -1)

I solve remove 
conf_mask = conf_mask.view(nB, -1)
and put on 
cur_gt_boxes = torch.FloatTensor([gx,gy,gw,gh]).repeat(nAnchors,1).t()
cur_ious = torch.max(cur_ious, bbox_ious(cur_pred_boxes, cur_gt_boxes, x1y1x2y2=False))
# conf_mask[b][torch.reshape(cur_ious, (5,13,-1))>sil_thresh] = 0
conf_mask[b][torch.reshape(cur_ious, (nA,nH,nW))>sil_thresh] = 0

https://github.com/marvis/pytorch-yolo2/issues/121
