### ISSUE TITLE
about the train dataloader

### ISSUE THREAD

**Issue by njtuzzy** [marvis/pytorch-yolo2#23]
@marvis in the train.py the train(epoch) function, why did you make a new dataloader for each epoch? can i move it out of train(epoch) function?

**Comment by zyyang** [comment]
Probably not.
There are data arguments changes, image sizes & colors.

**Comment by marvis** [comment]
the seen param is very hard to pass into listDataset which is cloned on many processers，so I create the dataloader to refresh seen param every epoch

**Comment by njtuzzy** [comment]
@marvis i asked this question because after 10 epoch, a runtime error will be poped out "inconsistent tensor sizes"...? will you have a guess what's going on?

**Comment by njtuzzy** [comment]
@mavis  so in my understanding, you create the dataloader in each epoch for multiple graphic cards usage in case thery are using the same data for training? on the other word, if i use one graphic card, it seems ok to move it out train function?

**Comment by marvis** [comment]
the input image is randomly resized in dataset.py.  the dataloader is processed on cpu，the seen param in dataset.py is used to control resize range which is very important at the early stage when the resize range should be narrow .

**Comment by njtuzzy** [comment]
due to the limitation of GPU memory size, i have to change the batch size from 64 to 32, but in dataset.py, it seems that the datalist use the 64 as an unit to calculate the changing of image size, so there will be an error. after i change tie value accroding to the batch size, it can work well

**Comment by buptxiaofeng** [comment]
@njtuzzy I am suffering from the same question. What is tie value and how can I change it?
