### ISSUE TITLE
the resize function is different

### ISSUE THREAD

**Issue by RickyWong33** [marvis/pytorch-yolo2#24]
It turns out that the origin darknet doesn't resize the image to network size directly:
https://github.com/pjreddie/darknet/blob/1b001a7f58aacc7f8b751332d3a9d6d6d0200a2d/src/demo.c#L185
```
buff_letter[0] = letterbox_image(buff[0], net.w, net.h);
```
-----------------
It uses a function called `letterbox_image`:
```
void letterbox_image_into(image im, int w, int h, image boxed)
{
    int new_w = im.w;
    int new_h = im.h;
    if (((float)w/im.w) < ((float)h/im.h)) {
        new_w = w;
        new_h = (im.h * w)/im.w;
    } else {
        new_h = h;
        new_w = (im.w * h)/im.h;
    }
    image resized = resize_image(im, new_w, new_h);
    embed_image(resized, boxed, (w-new_w)/2, (h-new_h)/2); 
    free_image(resized);
}
```
which means images are resized by their origin ratio and are padded to the network size.

In my implement of darknet, this does have some effects on the performance.

**Comment by marvis** [comment]
thanks for your information. Actually the images used in training are processed as square images. So there is no padding.

**Comment by RickyWong33** [comment]
You are right, keeping train and test in the same way is all right, but if turn darknet's weights to use in such way will have some visible differences.

**Comment by 4F2E4A2E** [comment]
@RickyWong33 does it mean that you could only train and test havin image sizes in a constant 1:1 relation or all the images _must_ have the exact same pixel size on both ends Xx:X:y (128:128) ?

**Comment by marvis** [comment]
@4F2E4A2E  You can padding the image into square shape. There is no need to resize the image to constant image size. The dataset loader will do the resize automatically.

**Comment by 4F2E4A2E** [comment]
But it is _necessary_ to pad it, right?
