### ISSUE TITLE
Error on demo

### ISSUE THREAD

**Issue by Spandan-Madan** [marvis/pytorch-yolo2#25]
I was getting this error - 

```
TypeError: view received an invalid combination of arguments - got (int, int, float, int, float, int), but expected one of:
 * (int ... size)
      didn't match because some of the arguments have invalid types: (int, int, float, int, float, int)
 * (torch.Size size)

```

I got multiple such errors but I was able to solve them because they were all happening because of the difference in division function of python2 and python3. Python2 returns ints while python3 returns floats in case of remainder. 

Strongly recommend either replacing all divisions by a // instead of / or wrapping all divisions in int() across the whole repository. Had to make changes in multiple files! 

Thanks a lot for this repo by the way. Great job!

**Comment by adamhrv** [comment]
Ran into same error in python3. For others, change lines 32-36 in `darknet.py` to:
 ```
x = x.view(B, C, int(H/hs), hs, int(W/ws), ws).transpose(3,4).contiguous()
x = x.view(B, C, int(H/hs*W/ws), hs*ws).transpose(2,3).contiguous()
x = x.view(B, C, hs*ws, int(H/hs), int(W/ws)).transpose(1,2).contiguous()
x = x.view(B, hs*ws*C, int(H/hs), int(W/ws))
```
and change line 149 to:
`pad = (kernel_size-1)//2 if is_pad else 0`

then run `python3 demo.py`

Otherwise, great repo. Significant speed increase over earlier version of pyyolo (about 75 FPS at 640x360px)

**Comment by alew3** [comment]
I also had to include the following on line 130 of utils.py to get it working:
num_anchors = int(num_anchors)
anchor_step = int(anchor_step)

**Comment by raggot** [comment]
Thank you both for the fixes. Got it working flawlessly with Python 3.5.
If anyone gets similar type-related errors, apply the changes proposed in both previous comments.
