### ISSUE TITLE
inconsistent tensor size at 20 epoch

### ISSUE THREAD

**Issue by tztztztztz** [marvis/pytorch-yolo2#27]
always got this error at 20 epoch 
```
2017-10-17 18:22:19 epoch 20, processed 331020 samples, lr 0.001000
/home/tz/Documents/python_envs/pytorch_env/local/lib/python2.7/site-packages/torch/tensor.py:293: UserWarning: self and other not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  return self.add(other)
/home/tz/Documents/python_envs/pytorch_env/local/lib/python2.7/site-packages/torch/tensor.py:309: UserWarning: self and other not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  return self.mul(other)
331068: nGT 114, recall 106, proposals 194, loss: x 2.379076, y 2.394640, w 2.035759, h 1.650143, conf 48.409969, cls 11.641119, total 68.510704
Traceback (most recent call last):
  File "train.py", line 258, in <module>
    train(epoch)
  File "train.py", line 147, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/home/tz/Documents/python_envs/pytorch_env/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/home/tz/Documents/python_envs/pytorch_env/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/tz/Documents/python_envs/pytorch_env/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/tz/Documents/python_envs/pytorch_env/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 109, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/tz/Documents/python_envs/pytorch_env/local/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 91, in default_collate
    return torch.stack(batch, 0, out=out)
  File "/home/tz/Documents/python_envs/pytorch_env/local/lib/python2.7/site-packages/torch/functional.py", line 66, in stack
    return torch.cat(inputs, dim, out=out)
RuntimeError: inconsistent tensor sizes at /pytorch/torch/lib/TH/generic/THTensorMath.c:2709

```
here is my command (I used the saved weight, /backup/00020.weights)
```
 python train.py cfg/voc.data cfg/yolo-voc.cfg backup/000020.weights
```
then I got the same error.
but if I used `darknet19_448.conv.23` as net's weights, there would be no error
I don't know why, is there some special change after epoch 20?

below is my package version
torch (0.2.0.post3)
torchvision (0.1.9)
cuda=8.0
python=2.7.6

**Comment by liangzimei** [comment]
i also meet the same question with you. have you solved it? Thank you...

**Comment by MengXinChengXuYuan** [comment]
I got this too...
Any ideas?

**Comment by MengXinChengXuYuan** [comment]
I don't know why but this error has a big connection with the batch size, if you lower the batch size and at some point there won't be any errors
See here [https://discuss.pytorch.org/t/a-problem-about-dataloader/4285](url)

**Comment by 4F2E4A2E** [comment]
Very weird, is there any pytorch-darknet alternative  worth of trying out?

**Comment by neuhzhj2012** [comment]
How u can successfully run train.py? Have u do other process?
I follow up the README.md，but [get error](https://github.com/marvis/pytorch-yolo2/issues/31).

**Comment by andresmafladelgado** [comment]
@4F2E4A2E I haven't found any other Pytotch / Darknet implementation either. Do you have nay suggestion?

Apparently this project cannot perform training successfully.

**Comment by MengXinChengXuYuan** [comment]
Hey guys, just believe in me :)
Change the batch size in yolo-voc to 16 ( if you got a gtx1080ti with 11GB, and if you have 4 gtx1080ti, just ignore me and rest the batch size to 64) and the "inconsistent tensor sizes" will just disappear

**Comment by marvis** [comment]
@tztztztztz The image size is changed every 64 samples, see
https://github.com/marvis/pytorch-yolo2/blob/master/dataset.py#L38
To make the same image size in one batch, the batch size should be divided by 64. However you can change 64 to any number.

**Comment by tztztztztz** [comment]
@marvis  thank you so much! :D
