### ISSUE TITLE
YOLO9000

### ISSUE THREAD

**Issue by abagshaw** [marvis/pytorch-yolo2#3]
Just wondering - it appears that there is not currently support for YOLO9000 (although I could be wrong). Any plans on adding this in the near future?

**Comment by marvis** [comment]
Do you mean training of yolo9000? I think inference is not a problem. Currently I am still struggling to reproduce the train result on pascal voc. And yolo9000 maybe prosponed until needed.

**Comment by abagshaw** [comment]
No, I was just talking about inference (although training would be awesome too :) ). I haven't tried plugging in `yolo9000.cfg` and `yolo9000.weights` (I will when I get a chance) but I was just looking at the code and https://github.com/marvis/pytorch-yolo2/blob/f3240543892ac9419dd2d6dc90cffc35f21d7e1d/detect.py#L15-L20 and it didn't seem that the yolo9000 labels were implemented so I assumed that `pytorch-yolo2` was not setup for YOLO9000 inference.

**Comment by wtnan2003** [comment]
Will "the Real-Time Detection on a Webcam" work  in the nearly future?

**Comment by marvis** [comment]
@wtnan2003  you can try the command below to do detection on a webcam real-time. 

python demo.py cfg/tiny-yolo-voc.cfg tiny-yolo-voc.weights
