### ISSUE TITLE
Has anyone had success training the model? How did you do it?

### ISSUE THREAD

**Issue by andresmafladelgado** [marvis/pytorch-yolo2#32]
Hello,

I have been following all the readme steps to train the model with the VOC Dataset, and then use it with my own data. However apparently there are a lot of people that have been experiencing issues.
as in: issue #27 issue #31 

I have fixed some of them but still the code is untrainable. I have been using:

Env1: Python 2.7, Pytorch 0.2.0 , CUDA 8.0, cudNN6.0, Ubuntu 16.04
Env2: Python 3.5, Pytorch 0.2.0, CUDA 8.0, cudNN6.0, Ubuntu 16.04

**Comment by marvis** [comment]
Two things needed to do for your own data:
1. padding your image into square size and modify your label files correspondingly.
2. change the resize strageties  in listDataset

**Comment by soumendukrg** [comment]
What do you mean by resize strategies in listDataset? Can you tell why do I need to do that?

**Comment by elixir-1** [comment]
What does resize strategy do in listDataset?
