### ISSUE TITLE
use python3.6

### ISSUE THREAD

**Issue by nianfudong** [marvis/pytorch-yolo2#36]
This project works well on Python 2.7. However, it can't works on Python 3.6. I find the reason is that the division operation is difference between Python2.7 and Python 3.6. e.g " anchor_step = len(anchors)/num_anchors " should be changed as " anchor_step = len(anchors)//num_anchors ".  After these changes, this program works well. I hope this could help others.

**Comment by marvis** [comment]
Thanks for you suggestion!
