### ISSUE TITLE
How to set the object_scale/noobject_scale/class_scale/coord_scale ？

### ISSUE THREAD

**Issue by MengXinChengXuYuan** [marvis/pytorch-yolo2#37]
I'm sorry but I'm so confused...
In the paper You Only Look Once: Unified, Real-Time Object Detection, they set:
object_scale=1
noobject_scale=0.5
class_scale=1
coord_scale=5

But in your work you set them as :
object_scale=5
noobject_scale=1
class_scale=1
coord_scale=1

Did I miss something ?

**Comment by marvis** [comment]
The paper you read is yolo1
