### ISSUE TITLE
Is it possible to resume model? 

### ISSUE THREAD

**Issue by hyer** [marvis/pytorch-yolo2#40]
I run the train.py with batch_size=32 on GTX1080 and found cuda error  (2): out of memory after 10 epoch. thanks!

**Comment by 4F2E4A2E** [comment]
Can you tell us the dimensions of your dataset / images?
Which CUDA and cuDNN?
Try it out with a lower batch size.

**Comment by hyer** [comment]
Thank. I have found the way to resume training by set the weight file at https://github.com/marvis/pytorch-yolo2/blob/7dc4e914e1bfb97c1f3cf156e3e103c9ff51586b/train.py#L73
