### ISSUE TITLE
cuda runtime error (59)

### ISSUE THREAD

**Issue by tghoshmo** [marvis/pytorch-yolo2#45]
Hi, 

When I am training with my own data set, I am getting the following error message:

2017-12-15 22:16:33 epoch 0, processed 0 samples, lr 0.000100
/usr/local/tensorflow/local/lib/python2.7/site-packages/torch/tensor.py:293: UserWarning: self and other not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  return self.add(other)
/usr/local/tensorflow/local/lib/python2.7/site-packages/torch/tensor.py:309: UserWarning: self and other not broadcastable, but have the same number of elements.  Falling back to deprecated pointwise behavior.
  return self.mul(other)
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:57: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [13,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.c line=32 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "train.py", line 255, in <module>
    train(epoch)
  File "train.py", line 164, in train
    loss = region_loss(output, target)
  File "/usr/local/tensorflow/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tarutal/pytorch-yolo2/region_loss.py", line 183, in forward
    print('%d: nGT %d, recall %d, proposals %d, loss: x %f, y %f, w %f, h %f, conf %f, cls %f, total %f' % (self.seen, nGT, nCorrect, nProposals, loss_x.data[0], loss_y.data[0], loss_w.data[0], loss_h.data[0], loss_conf.data[0], loss_cls.data[0], loss.data[0]))
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCStorage.c:32

I would appreciate if anybody could help me out.

Thanks.

**Comment by heitorrapela** [comment]
Same error here, when I try to train with 2 classes

**Comment by heitorrapela** [comment]
Hey there, to solve this problem try to put the number of classes in cfg file and in .data file
Something like: classes = qtt
And in cfg file architecture you need to change the filters from last conv layer.
