### ISSUE TITLE
Training on a part of dataset

### ISSUE THREAD

**Issue by AmIr-KinG** [marvis/pytorch-yolo2#47]
Hi,
I'm facing low memory problem and I wish to train on a part of dataset.
Whats the best way to solve this problem? Using sampler? Perhaps changing batch size?

**Comment by TaihuLight** [comment]
To set samaller batch size can solve the problem

**Comment by heitorrapela** [comment]
The size of image is changed every 10 epochs during the train phase, so in .cfg file you have height=416, width=416, but it can be resized to these range 300~608, like 608x608. You can calculate how much memory you will need to your train, something like width*width*channel*batch_size. 

Example: batch_size = 6 (I like to put subdivision = 64, but you can try 8, depends of GPU VRAM)
I have a GPU of 8gb's, If you put the max of the size (it's random value between 300~608, you can see in dataset.py file), you will need 608*608*3*6 = ~6.65gb of memory.
