### ISSUE TITLE
where is the do_detect method in tiny_yolo.py file?

### ISSUE THREAD

**Issue by skrish13** [marvis/pytorch-yolo2#50]
https://github.com/marvis/pytorch-yolo2/blob/master/models/tiny_yolo.py#L110

Hi, I've looked through the codebase and was unable to find it, could you help me where is it and what does it do?

**Comment by dhpollack** [comment]
do detect is in the utils.py file

**Comment by skrish13** [comment]
riight. not sure how i missed it. thanks!
