### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by Heng14** [marvis/pytorch-yolo2#76]
Great job! But I met a problem:
File "/home/nebulalink/heng/pytorch-yolo2/darknet.py", line 265, in load_weights
    start = load_conv_bn(buf, start, model[0], model[1])
  File "/home/nebulalink/heng/pytorch-yolo2/cfg.py", line 175, in load_conv_bn
    conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w 
RuntimeError: The expanded size of the tensor (3) must match the existing size (864) at non-singleton dimension 3

It seems that it is related to the version of torch (0.2). Anyone has a solution?
Thank you!

**Comment by pengfeix** [comment]
I have the same question with you.Do you solve it?

**Comment by Heng14** [comment]
Hi @pengfeix , thank you for the comment. Yeah, I use opencv2 and pytorch 0.3 (both in anaconda) and it can work now~ Good luck!

**Comment by ankitdhall** [comment]
@Heng14 @pengfeix how was the issue resolved? I have a similar error.
When I run `print(torch.__version__)` I get `0.4.0a0+2e156f3`.

How did you solve the issue? Thanks.

**Comment by Heng14** [comment]
Hi @ankitdhall I install pytorch with conda like I said in the last comment. It can work. So I recommend that you use conda~ Thank you!

**Comment by ankitdhall** [comment]
@Heng14 thank you for the quick response. I cannot use conda on my architecture so I shall try to install v0.3.0 through source. Hopefully, it works!
