### ISSUE TITLE
GPU out of memory when training on VOC

### ISSUE THREAD

**Issue by taot** [marvis/pytorch-yolo2#85]
I ran into GPU out of memory error when I am training pytorch-yolo2 on VOC dataset

I have one GeForce GTX 1080Ti with 12 GB memory, my system is Arch Linux with cuda 9.1 installed, and use Anacoda with pytorch-0.3.1, cuda91-1.0 installed

`python train.py cfg/voc.data cfg/yolo-voc.cfg weights/darknet19_448.conv.23`

The GPU memory shoot up quickly after I started the training process, and then got out of memory error. Here' the error message:
```
   22 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   23 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   24 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   25 route  16
   26 conv     64  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x  64
   27 reorg              / 2    26 x  26 x  64   ->    13 x  13 x 256
   28 route  27 24
   29 conv   1024  3 x 3 / 1    13 x  13 x1280   ->    13 x  13 x1024
   30 conv    125  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 125
   31 detection
2018-04-11 15:56:26 epoch 0, processed 0 samples, lr 0.000100
/home/taot/opt/miniconda3/lib/python3.6/site-packages/torch/tensor.py:305: UserWarning: self and other not broadcastable, but have the same number of
elements.  Falling back to deprecated pointwise behavior.
  return self.add(other)
/home/taot/opt/miniconda3/lib/python3.6/site-packages/torch/tensor.py:321: UserWarning: self and other not broadcastable, but have the same number of
elements.  Falling back to deprecated pointwise behavior.
  return self.mul(other)
64: nGT 138, recall 52, proposals 13, loss: x 96.290939, y 107.530678, w 1720.617676, h 1432.369141, conf 6685.756836, cls 407.097076, total 10449.662109
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518244507981/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 262, in <module>
    train(epoch)
  File "train.py", line 165, in train
    output = model(data)
  File "/home/taot/opt/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/taot/src-repo/pytorch-yolo2/darknet.py", line 91, in forward
    x = self.models[ind](x)
  File "/home/taot/opt/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/taot/opt/miniconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/taot/opt/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/taot/opt/miniconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/home/taot/opt/miniconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1518244507981/work/torch/lib/THC/generic/THCStorage.cu:58
```

Has anybody seen this issue? In the checked-out repository, I see it's configured with 4 GPUs, is it not supposed to train on a single GPU?

**Comment by ayooshkathuria** [comment]
The default batch size in `yolo-voc.cfg` file is 64. As I remember, training with that batch size took up around 21 GB of GPU memory (My Tesla K80 is 12 x 2 GB). SO what you want to do is go to the file `cfg/yolo-voc.cfg` and edit the batch size to, say 32 or maybe 24. ALSO, decrease the learning rate by the same factor which you have decreased the batch size for stable training. So, if you go for a batch of 32, halven the training rate.

**Comment by wxjeacen** [comment]
Same problem. will have a try.

**Comment by Bigwode** [comment]
try to decrease the batch_size maybe can solve this problem

**Comment by taot** [comment]
Thanks a lot! Will have a try for smaller batch_size.

**Comment by taot** [comment]
I am able to run training when setting batch_size to 32, on my GeForce GTX 1080Ti. It consumes about 8.5GB memory.

**Comment by puyangma** [comment]
@taot Thanks for your post. This is very helpful. You successfully trained with batch_size 32, I wonder if you remember how did you deal with multi-scale training? I am using a Tesla K80 GPU and batch_size 32, but encountered OOM error after 60 epochs due to multi-scale training.

**Comment by htt1084** [comment]
@puyangma I have the same problem actually. What I did was to reduce the values in the multi-scale training a bit (which would hurt mAP).

**Comment by taot** [comment]
> @taot Thanks for your post. This is very helpful. You successfully trained with batch_size 32, I wonder if you remember how did you deal with multi-scale training? I am using a Tesla K80 GPU and batch_size 32, but encountered OOM error after 60 epochs due to multi-scale training.

@puyangma Sorry I couldn't help here. I don't think I did the multi-scale training, I was just playing with the model for a little while but didn't go deep into that.
